server:
  port: 8005

spring:
  application:
    name: cloud-provider-payment8001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     #mysql驱动包
    url: jdbc:mysql://39.97.102.8:3306/nszspringcloud?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: Luo1011.
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ns.com.ns.springcloud.entities  # 所有Entity 别名类所在包