server:
  port: 7001

spring:
  application:
    name: cloud-eureka-server7001
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     #mysql驱动包
    url: jdbc:mysql://39.97.102.8:3306/nszspringcloud?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: Luo1011.
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ns.springcloud.entities  # 所有Entity 别名类所在包

eureka:
  instance:
    hostname: localhost  #eureka服务端的实例名字
  client:
    register-with-eureka: false    #表识不向注册中心注册自己
    fetch-registry: false   #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址


