server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名

#          需要注意的是uri的协议为lb，表示启用Gateway的负载均衡功能。
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/find/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
#        请求地址    curl http://localhost:9527/payment/lb --cookie "username=ns" -H"X-Request-Id:123"
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]  #此路线符合 2017 年 1 月 20 日 17：42 山地时间 （丹佛） 之后提出的任何请求。
            - After=2021-03-03T15:15:58.081+08:00[Asia/Shanghai]   #在这个时间之后访问才有效 可以提前上线 到点起效 秒杀
            - Cookie=username, ns       #cookie  此路由匹配具有已命名的 Cookie 的请求，其值与常规表达式匹配
            - Header=X-Request-Id, \d+  #如果请求的header命名为其值与常规表达式匹配（即其值为一个或多个数字），则此路由匹配。X-Request-Id\d+
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka   #单机
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
