server:
  port: 8005

spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver     #mysql驱动包
    url: jdbc:mysql://39.97.102.8:3306/nszspringcloud?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: Luo1011.


eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true.  这里当做客户端不注册进去了
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间  秒
  ReadTimeout:  5000
  #指的是建立连接后从服务器读取到可用资源所用的时问
  ConnectTimeout: 5000

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.ns.springcloud.service.PaymentFeignService: debug


